### ISSUE TITLE
visible sample collage image

### ISSUE THREAD

**Issue by DreadKnight** [wtactics/art#3]
The `README.MD` file should contain a sample collage to showcase this gallery in order to give visitors a basic idea regarding the quality and style, in order to increase engagement, usage and project success.

**Comment by ngoeminne** [comment]
That could be indeed useful.  We do have a searchable collection preview at https://arcmage.org/artwork/

**Comment by ngoeminne** [comment]
I've added a samples.md with all thumbnails
